### ISSUE TITLE
Not found : @snyk/registry

### ISSUE THREAD

**Issue by IanVS** [Snyk/snyk#10]
Hi, I attempted to clone this repo and `npm i`, but I received the following error:

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/ianvs/.nvm/versions/node/v5.3.0/bin/node" "/Users/ianvs/.nvm/versions/node/v5.3.0/bin/npm" "i"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code E404

npm ERR! 404 Not found : @snyk/registry
npm ERR! 404
npm ERR! 404  '@snyk/registry' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'snyk'
```

I was attempting to use the master version, because I'm using npm@3 and figured I could help test out some of the changes you're making to add support for npm@3.

**Comment by remy** [comment]
You won't be able to install the devDeps because we use some private snyk fixtures during tests. In you `npm install --prod` if should work.

However, the npm@3 work isn't in this repo, it gets merged across from another repo. I am trying to extract out the logic into full open source, and it is very close, but I can't post anything here just yet.

Does that answe your issue?

**Comment by IanVS** [comment]
OK sure, I just figured changes to support npm@3 would show up in master more quickly.  I've subscribed to https://github.com/Snyk/snyk/issues/4, and will be willing to beta-test whenever you say it's ready for a try.

**Comment by remy** [comment]
Trust me, its appreciated. The initial change was very easy, but supporting extraneous packages has been the struggle (and npm@3 doesn't have the logical tree quite right yet either). I'm very close, and should be able to share the module tomorrow (1 known bug left to solve).
