### ISSUE TITLE
[🐛] .snyk file from root directory ignored

### ISSUE THREAD

**Issue by artur1211** [snyk/snyk#1237]
- `node -v`: v10.17.0
- `npm -v`: 6.11.3
- `snyk -v`: 1.348.2
- OS: OSX, Linux
- Command run: snyk test --all-projects --detection-depth=2

### Expected behaviour
Till version 1.348.0 .snyk file with ignore list has been taken into account when running this command.

### Actual behaviour
From version 1.348.1 .snyk file from root dir is ignored

### Steps to reproduce
Project with .snyk file in root dir and many modules
Run snyk test --all-projects --detection-depth=2

**Comment by artur1211** [comment]
I can see that recently this issue
https://github.com/snyk/snyk/issues/1014
has been merged, maybe it is somehow connected.

**Comment by lili2311** [comment]
👋 Hi @artur1211 unfortunately that was a bug, each `.snyk` file is expected next to the each manifest that is scanned. This was fixed in the issue you linked to. This was a regression introduced during `--all-projects` support unfortunately.

**Comment by lili2311** [comment]
Just wanted to provide more context here on what is the intended behaviour and why this fix needed to go in:
- Snyk has always allowed for a `.snyk` policy file to be created and maintained *next to the manifest* being tested. This is to allow each *project* to ignore/patch and configure these projects.
- With the addition of auto-detection via `--all-projects` a bug was introduced that meant the policy was looked for *in the location where the command is run* instead of the next to the manifest. This means that any policy you create will only *happen* to work because of the bug and will not be picked up if you were to run a `snyk test` command in a folder above for example. Being able to run `snyk test folder1 folder2` has also always been a feature in the CLI and it is expected that any policies deeper down are correctly applied to each respective project.

This unfortunately means that there have been some tests where the `.snyk` files were not picked up and now with the fix in place those tests follow the original intended behaviour but unfortunately it means the behaviour you expect here is not going to work the same way.

My suggestion here would be:
- copy your `.snyk` file to each folder where the manifest you are scanning is
- ensure this file is specific to that project (you may want to ignore the same vuln in one project but not the other)
- you can also rely on the Organisation Ignores in the UI with are tied to the project by it's ID ( we want to move away from ignoring in the CLI eventually)

When a PR is opened by Snyk the `.snyk` file next to the manifest will be updated, this another important point as the projects may be both imported in UI and CLI.

**Comment by artur1211** [comment]
Thank you for explanations

**Comment by lili2311** [comment]
@artur1211 just realised that perhaps you can achieve exactly what you had if you use `--policy-path=path/to/.snyk`, please let me know if this helps

**Comment by artur1211** [comment]
Actually I have already divided my .snyk file between modules. But If I Have some free time I will check if this solution works.

**Comment by rvvincelli** [comment]
> @artur1211 just realised that perhaps you can achieve exactly what you had if you use `--policy-path=path/to/.snyk`, please let me know if this helps

Thanks for mentioning this, without specifying the policy file my ignores get ignored when giving: `snyk test --all-projects --severity-threshold=high`, so yes `--policy-path=.snyk` must be added. After 20 minutes scratching my head for this any pun is intended :)

**Comment by stevewithey** [comment]
The challenge with this I'm having is around handling the mix of potential scenarios when using --all-projects:
- Root of the repo has a global .snyk file (which by default would be ignored)
- Root of the repo has global .snyk file and sub-projects have their own .snyk files
- No global .snyk file in root or project-level .snyk files
- No global .snyk file in root, but project-level .snyk files

It would be great if when using --all-projects Snyk could manage this hierarchy itself, but I'm being forced to write handling for when to pass in the --policy-path argument and when not to
