### ISSUE TITLE
[🙏] Pin dependencies to ensure a known working Snyk version

### ISSUE THREAD

**Issue by LoganBarnett** [snyk/snyk#1381]
- `Language / Project Type:` JavaScript
- `Package Manager / Build Tool:` `npm`

**Describe the user need**
~~Snyk should use `package-lock.json` or `yarn.lock` as a means of ensuring continuous stability as Snyk's dependencies change.~~

Originally this ticket asked to introduce `package-lock.json` or `yarn.lock` as a means of pinning Snyk's dependencies. Parts of this ticket have been edited to make it a more general ask of just pinning the dependencies directly.

**Describe expected behaviour**

When installing Snyk, we should always receive a known, working version of Snyk in combination with all of the dependencies in the exact, known state bound to said version of Snyk. 

**Additional context**

Without this, installs of Snyk are captured at the moment of install. We can run into issues such as (recently at time of writing) #1377. To my understanding, this change broke Snyk with no changes to Snyk at all - the change to `needle` effectively circumvented all of Snyk's quality gates. It looks like everyone jumped on it and the turnaround time was hours. That's awesome!

I understand that there has been a deliberate choice to ignore `package-lock.json` (#223) in this repository. This ticket serves as a plea to revisit this decision. Even if we're all damned to the timing of installing Snyk as a global package, those of us installing it locally as a `devDependency` should at least be spared this fate. While our projects can secure a lock file at moment of install, it's still dependent upon that install time and not Snyk's moment of release when we all knew everything was good :)

**Comment by lili2311** [comment]
Hi @LoganBarnett The [package-lock.json](https://docs.npmjs.com/files/package-lock.json) & [yarn.lock](https://classic.yarnpkg.com/en/docs/yarn-lock/) are ignored on publishing to `npm` a library, libraries do ignore the lockfile during development often to have the same dependencies a user would get after installing Snyk. 
Unfortunately the upstream libraries used are not possible to control (we can pin then as we did in this case), especially when there is a trust that the next *patch* or *minor* version is indeed following semver and is backwards compatible.It is a delicate balance between wanting to have dependencies keep moving slowly forward and updating and being stuck with an older version of a dependency (and missing out on nice new improvements!)

**Comment by LoganBarnett** [comment]
@lili2311 thanks for the prompt reply!

I was not aware that `package-lock.json` and `yarn.lock` were effectively ignored when consuming a library. In that case I would instead suggest that we pin Snyk's dependencies. I hear from you that you want to get improvements as they come in, and I agree keeping current is highly desirable. My ultimate ask is that any changes to dependencies go through the same rigors that any other change would go through. I can rephrase the ticket to make that ask instead :)

At the risk of waning philosophically: I suggest that Semver's most delicious myth is that we can control what breaks our consumers with our intent alone. No change is absent of risk. Saying that a given change is more or less risky is essentially expressing a bias to our work. Historically when I have done this, my QA counterparts have laughed at me. I would imagine many of us have had similar stories.

At my workplace we have constructed a library that upgrades the `dependencies` and `devDependencies` of a Node.js project, runs the tests, and commits the results if the tests are successful. If there is interest in such a thing from the Snyk team, perhaps I could work with my org to see about getting it open sourced.

**Comment by JackuB** [comment]
You are right, but there isn't a good solution as far as we know. Not aware of any effort in NodeJS/npm to improve this state :/

Snyk CLI does not ship with vendored/embedded dependencies, but only a manifest, package.json, of what it needs to run. Since npm dependency trees runs _very deep_, fixing a top-level dependency in place serve a little value—**its whole tree is using ranges.**

As for ways to have more control over that tree, you have limited options within the NodeJS ecosystem. You could vendor/embed (Webpack/Rollup) those dependencies, but then you lose visibility into what's in your tree, as there isn't a mechanism to surface that.

We opt in for an optimistic best-effort approach, that's also _natural_ to how NodeJS ecosystem works, with in-range updates. This way, the **consumer of the CLI can fix dependencies in place, with their own package-lock.json**. But yeah, I would sleep better if I could ensure that any 3rd party in the tree can't break our CLI.

Anyway, we also release an executable build with frozen and embedded dependencies: https://github.com/snyk/snyk/releases

**Comment by LoganBarnett** [comment]
@JackuB those are excellent points!

I did find that npm's [shrinkwrap](https://docs.npmjs.com/configuring-npm/shrinkwrap-json) seems to be designed for cases like this one - where the end product is a tool such as Snyk. Though there are places where you wouldn't want to publish a shrinkwrap, so it's more of a design decision.

In the mean time leaning on frozen builds linked above seems sensible. I'm not sure how the Snyk team feels about shrinkwrap but with a workaround in hand my org's immediate needs are addressed. I'm happy to close this ticket out or leave it open as a means of looking into shrinkwrap or some other mechanism.

Thanks!

**Comment by JackuB** [comment]
We've looked into the shrinkwrap and with current Snyk CLI usage, it would be problematic:

> It’s strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

We are looking into first moving Snyk CLI out from the users' dependency trees, possibly by using `npx` instead of adding Snyk as a project dependency. Once we do that, distributing the shrinkwrap file might be a sensible option.

I'm closing this issue for now, thanks!
