### ISSUE TITLE
[🐛] Snyk Monitor Out of Sync With Snyk Advisor: ripple-keypairs@1.0.3

### ISSUE THREAD

**Issue by drsavant-pub** [snyk/snyk#1660]
- `node -v`: 14.15.4
- `npm -v`: 6.14.10
- `snyk -v`: 1.460.0
- OS: Windows 8.1
- Command run: (`snyk monitor')

I'm new to Snyk, but I've been running 'snyke monitor' locally, updating packages, and then rerunning, and each time the issue is fixed (when it can be fixed), until now.

**Please note:**  I uninstalled and reinstalled to: ripple-lib@1.9.1

### Expected behaviour
I expected one less issue: ripple-lib@1.9.1 › ripple-keypairs@1.0.3 › _**elliptic@6.5.3**_ [link](https://app.snyk.io/org/drsavant-pub/project/31abbcd1-3f58-479d-a446-9345ac64a689/history/c9422c9f-0898-4cb4-9cd9-af5e0ea053a7) since it was fixed in [ripple-keypairs@1.0.3](https://github.com/ripple/ripple-keypairs/blob/master/package.json) See _**elliptic: 6.5.4**_ as reported in snyk advisor [here](https://snyk.io/advisor/npm-package/ripple-keypairs) and [here](https://snyk.io/advisor/npm-package/elliptic).

### Actual behaviour
snyk monitor is still reporting: ripple-lib@1.9.1 › ripple-keypairs@1.0.3 › **_elliptic@6.5.3_** [Here](https://app.snyk.io/org/drsavant-pub/project/31abbcd1-3f58-479d-a446-9345ac64a689/history/c9422c9f-0898-4cb4-9cd9-af5e0ea053a7)

### Steps to reproduce
[Snyk Monitor](https://app.snyk.io/org/drsavant-pub/project/31abbcd1-3f58-479d-a446-9345ac64a689/history/c9422c9f-0898-4cb4-9cd9-af5e0ea053a7) see  **ripple-lib@1.9.1 › ripple-keypairs@1.0.3 › elliptic@6.5.3**
[Snyk Advisor](https://snyk.io/advisor/npm-package/ripple-keypairs) as you can see no issues because it was already updated: [Here](https://github.com/ripple/ripple-keypairs/blob/master/package.json) 3-days ago.

### Debug log
NA

### Screenshots
NA

**Comment by lili2311** [comment]
hi @drsavant-pub I am 👀 at the links you have shared. While I do that I wanted to share how `snyk monitor` is different to what you see in Snyk Advisor:
- `snyk monitor` will detect a local lockfile or `node_modules` on your local machine. This means the dependencies are stuck at a certain version at the time that you ran `npm i`. If one of the packages since then has a new version and still matches the semver range withint the `package.json` a *fresh* `npm i` will now resolve differently. (Fresh being deleting a lockfile or `node_modules`). So you could have different transitives on your machine when you run `snyk monitor` vs if you deleted `node_modules` or lockfile and run it again
- Snyk advisor only reports on the vulnerabilities in a particular package with the assumption of everything being absolute latest.

To help understand what your local dependencies look like could you share `npm ls` output?

**Comment by lili2311** [comment]
@drsavant-pub taking a look at your project I can see we have stated the same on the issues as my message above. If you expand an issue you will see something like:
```
Your dependencies are out of date, otherwise you would be using a newer X than X@Y. Try relocking your lockfile or deleting node_modules, reinstalling and running snyk wizard. If the problem persists, one of your dependencies may be bundling outdated modules.
```
Please follow this advice and do a clean install: 
- delete `node_modules`
- delete `package-lock.json` or `yarn.lock` you have
- run `npm i` again

Does this answer your question and solve the issue you are seeing?

**Comment by lili2311** [comment]
@drsavant-pub did the above solve the issue for you? Can we close this issue?

**Comment by lili2311** [comment]
@drsavant-pub closing this issue, please re-open if you are having trouble still.
