### ISSUE TITLE
feature request: option to suppress exit / error code

### ISSUE THREAD

**Issue by DanielRuf** [snyk/snyk#191]
### Expected behaviour
An option to suppress the exist code like auditjs does.

### Actual behaviour
No option to suppress the exit code.
Always exists with `error Command failed with exit code 1.`

**Comment by adrukh** [comment]
@DanielRuf thanks for this suggestion! Can you explain the flow in which you are interested in this result?

Our general suggestion here would be to use `snyk test || true` if you are interested in the report, but don't want to fail a CI build, for example. I wonder if this can work here, or if the use case warrants a different solution.

**Comment by DanielRuf** [comment]
> snyk test || true

This will probably not work in all environments and this is not very self describing.

In general we want to suppress and prevent failing builds in some cases but show the report by providing the needed flag based on the environment or specific environment variables.

**Comment by DanielRuf** [comment]
> @DanielRuf If I understood this correctly, you want your build to still pass, even with failures, but make sure it still output a report etc?

Exactly. Like the `|| true` solution but we need a flag for `snyk`.

**Comment by robcresswell** [comment]
@DanielRuf Hey Daniel, thanks for the quick response. We've had a discussion, and don't feel this is something we'd like to add to the CLI right now, as we feel it's a bit of an edge case and has a straightforward workaround. We'll keep it in mind, and if we receive more demand we'll re-evaluate. Hope that's okay :innocent:

**Comment by mehdiben7** [comment]
> @DanielRuf Hey Daniel, thanks for the quick response. We've had a discussion, and don't feel this is something we'd like to add to the CLI right now, as we feel it's a bit of an edge case and has a straightforward workaround. We'll keep it in mind, and if we receive more demand we'll re-evaluate. Hope that's okay 😇

If I may, I'd like to suggest another perspective:

In the case of a CI pipeline, we may need to obtain a list of CVEs, for example, for a large number of projects. The `|| true` solution works very well, of course, if the tool has actually been able to do its scan properly. The problem lies in cases where the tool has not been able to scan the project correctly. In such cases, we can't tell the difference between a non-zero code due to the presence of a vulnerability and a non-zero code due to a configuration error, or because the tool was unable to perform its test. I know this isn't on your agenda at the moment, but I have a feeling it could help those who use your tool at DevOps level.
