### ISSUE TITLE
snyk added as dependency - should be devDependency?

### ISSUE THREAD

**Issue by getglad** [Snyk/snyk#24]
This is just a suggestion, but (like the title of the issue suggests) it makes more sense to me that the wizard would add snyk to `devDependencies` instead of `dependencies` - thoughts?

**Comment by adam-moss** [comment]
I seem to remember reading somewhere, can't find where, this was because when installing with `--production` you wouldn't then have `snyk protect` available.  There was more to it than that though I'm sure.

**Comment by remy** [comment]
Hi @getglad, @adam-moss is right, it's because the `snyk protect` wouldn't work when a third party download and installed your package.

However, I've got a change request in my current sprint that means that if you select to test (in the wizard), but not protect (or you don't need to protect because you're not using patches), then Snyk will go into your devDeps.

I'll post here once it's live and which version it shipped under.

**Comment by remy** [comment]
A bit late to comment on this, but snyk has been updated so that when a user selects to add tests (during the wizard), snyk is only added as a devDep. If you chose to protect, snyk is added as a production dep.
