### ISSUE TITLE
npm seems to be used for yarn and npm?

### ISSUE THREAD

**Issue by DanielRuf** [snyk/snyk#249]
- `node -v`: 10.12.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.100.1
- Command run:

Not sure but `snyk-test` contains the following:
```
if (['npm', 'yarn'].indexOf(packageManager) >= 0) {
    return require('./npm')(root, options);
  }
```
Shouldn't it be yarn when yarn Yarn is set as `options.packageManager`?
If so I can create a PR.

**Comment by lili2311** [comment]
This is simply bad name on our part which is left over since a recent refactor 🙈 The folder should be renamed to `node`, we use a `snyk-nodejs-lockfile-parser` which can correctly process yarn vs npm given the file we are working with: https://github.com/snyk/snyk/blob/master/src/lib/snyk-test/npm/index.js#L146

You are welcome to raise this PR 🎉 that would be super helpful

**Comment by lili2311** [comment]
Closing this one, please re-open if there is anything further we can help with
