### ISSUE TITLE
CLI for Apple Silicon

### ISSUE THREAD

**Issue by Moser-ss** [snyk/snyk#2793]
I like to have a standalone executable, especially when I can use brew to install the binary, but I was surprised that Snyk still didn't provide a version for Apple Silicon aka darwin arm64. Any plans to release this arch?

**Comment by JackuB** [comment]
We've recently released a support for linux/arm64 https://updates.snyk.io/snyk-cli-standalone-executables-for-linux-arm64-223482. M1 build is on our radar, we are waiting for CircleCI (or GitHub Actions) to support M1 environment in order to have automated testing in our CI/CD.

See https://updates.snyk.io for future updates
