### ISSUE TITLE
Terms & Conditions notice

### ISSUE THREAD

**Issue by ghengeveld** [Snyk/snyk#3]
Is it really necessary to pollute the `npm install` output by printing a T&C notice from the postinstall script? I'd much prefer a less intrusive method.

**Comment by johannakoll** [comment]
Hello Gert, 

Legally we must give users the opportunity to read the T&Cs before using the tool. The current solution is the least intrusive way we found that still allows us to comply with that. Can you think of a better way to do it though?

Johanna

**Comment by ghengeveld** [comment]
Isn't it enough to mention it on the website? I'm not aware of any other projects dealing with the same issue, so I can't really comment on better solutions. I was thinking of asking confirmation when running Snyk the first time, but that would be tricky when your CI server re-installs Snyk each time it builds. Also it would be more intrusive, not less.

**Comment by johannakoll** [comment]
I agree, we would totally prefer to have it only on the website, but legally we have to give users a chance to see it before use - and because you can use Snyk in the command line without ever signing up on our site, we had to put it there. We put it at the postinstall step for exactly the reason you pointed out. But appreciate it's not an ideal experience...I'll capture your feedback so we can revisit this in the future.

**Comment by johannakoll** [comment]
We did revisit this, talked to the lawyers again, and looked at best practice for how others are handling it. Got green light to remove the API notice from postinstall, just deployed.
