### ISSUE TITLE
snyk test finds more vulnerabilities than snyk.io

### ISSUE THREAD

**Issue by chapati23** [snyk/snyk#34]
- `node -v`: **6.3.0**
- `npm -v`: **3.10.3**
- `snyk -v`: **1.17.0**
- Command run: **snyk test**
### Expected behaviour

Outputs the same vulnerabilities as the project page on snyk.io
### Actual behaviour

Outputs more vulnerabilities than the project page on snyk.io
### Steps to reproduce
1. Check vulnerabilities [on snyk.io](https://snyk.io/test/github/chapati23/snyk-auth0-issue) and find 1 HS vulnerability
2. Clone https://github.com/chapati23/snyk-auth0-issue to your local machine
3. Run `snyk test` and find 1 HS and 1 MS vulnerability
4. See the following output:

![screen shot 2016-07-14 at 12 19 37](https://cloud.githubusercontent.com/assets/117495/16836312/42e3f680-49bd-11e6-9027-71ccfb5451cb.png)

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
$ snyk test --debug
  snyk test +0ms { _: [ [Circular] ], debug: true }
  snyk checking for cli updates +281ms
  snyk add +14ms local true
  snyk policies found +574ms [ '/Users/felipe/projects/snyk-auth0-issue',
  '/Users/felipe/projects/snyk-auth0-issue/node_modules/snyk' ]
  snyk add +0ms policies 2
  snyk add +0ms packageName snyk-auth0-issue
  snyk add +0ms packageVersion 1.0.0
  snyk add +0ms package snyk-auth0-issue@1.0.0
  snyk add +342ms vulns-pre-policy 4..
  snyk add +8ms vulns 4
Error: ✗ High severity vulnerability found on negotiator@0.5.3
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:negotiator:20160616
- from: snyk-auth0-issue@1.0.0 > auth0-lock@9.2.1 > auth0-js@6.8.3 > winchan@0.1.2 > express@3.21.2 > connect@2.30.2 > compression@1.5.2 > accepts@1.2.13 > negotiator@0.5.3
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found on negotiator@0.5.3
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:negotiator:20160616
- from: snyk-auth0-issue@1.0.0 > auth0-lock@9.2.1 > auth0-js@6.8.3 > winchan@0.1.2 > express@3.21.2 > connect@2.30.2 > serve-index@1.7.3 > accepts@1.2.13 > negotiator@0.5.3
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ Medium severity vulnerability found on qs@0.6.6
- desc: Denial of Service (Memory Exhaustion)
- info: https://snyk.io/vuln/npm:qs:20140806
- from: snyk-auth0-issue@1.0.0 > qs@0.6.6
Upgrade direct dependency qs@0.6.6 to qs@1.0.0

✗ Medium severity vulnerability found on qs@0.6.6
- desc: Denial of Service (Event Loop Blocking)
- info: https://snyk.io/vuln/npm:qs:20140806-1
- from: snyk-auth0-issue@1.0.0 > qs@0.6.6
Upgrade direct dependency qs@0.6.6 to qs@1.0.0

Tested 387 dependencies for known vulnerabilities, found 3 vulnerabilities, 4 vulnerable paths.

Run `snyk wizard` to address these issues.
    at /Users/felipe/.nvm/versions/node/v6.3.0/lib/node_modules/snyk/cli/commands/test.js:193:17
    at tryCallOne (/Users/felipe/.nvm/versions/node/v6.3.0/lib/node_modules/snyk/node_modules/promise/lib/core.js:37:12)
    at /Users/felipe/.nvm/versions/node/v6.3.0/lib/node_modules/snyk/node_modules/promise/lib/core.js:123:15
    at flush (/Users/felipe/.nvm/versions/node/v6.3.0/lib/node_modules/snyk/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  snyk { command: 'test', args: [ { debug: true, loose: true } ], metadata: { local: true, policies: 2, packageName: 'snyk-auth0-issue', packageVersion: '1.0.0', package: 'snyk-auth0-issue@1.0.0', 'vulns-pre-policy': 4, vulns: 4 }, version: '1.17.0', os: 'OS X El Capitan', nodeVersion: 'v6.3.0', id: '12345', ci: false } +4ms
```

**Comment by remy** [comment]
Hi @chapati23 – I'm just picking this up now and taking a look.

I'll report back when I know where the issue is and let you know progress on resolving.

Thanks for raising the issue!

**Comment by guypod** [comment]
@chapati23, we got to the root of the problem - you uncovered an interesting scenario 😄 

The `auth0-js` package pulls in `qs` not from npm, but rather from this github repo: https://github.com/jfromaniello/node-querystring

That GitHub repo has a package.json file that states it's `qs@0.6.6` - a vulnerable version. 
The CLI pulled in the version from that package.json, thus marking it vulnerable, while the web based version relied on the version that pointed to it, skipping it.

It's not obvious whether we should or shouldn't report this git repo as vulnerable. After all, it's possible the repo was cloned in order to fix the vulnerability, and did so. However, after some conversation we determined that if a git repo claims it's a certain version, it's better to assume that's true than not. In other words, the CLI is correct, and we'll proceed assuming such repos are vulnerable. 

Either way, this confused our remediation. Since the version wasn't pulled from npm, we can't really guide you as to how to upgrade it away. You should be able to use the wizard to patch the vulnerability (our [patches for `qs`](https://snyk.io/vuln/npm:qs:20140806#snyk-patches) go back to version 0.6.5), assuming it that repo hasn't changed its files. 

We'll update the product to report these issues on the web, and to provide the right context for them. 
We'll also submit a pull request to https://github.com/auth0/auth0.js asking them to switch to using the relevant qs version, or at least upgrade the git clone they're using. 

In the meantime, I believe odds are you indeed have this vulnerability, but our patches don't seem to work, also confused by this problem. If this is production system, may be worth creating a temporary clone of auth0-js and use that in the meantime.

**Comment by chapati23** [comment]
thanks for the quick feedback, my project is not yet in production so it's no emergency.

i've already opened an issue for the other discovered vulnerability: https://github.com/auth0/auth0.js/issues/178

**Comment by adrukh** [comment]
Closing this one for now.
