### ISSUE TITLE
Confusing for a newcomer

### ISSUE THREAD

**Issue by JohnReedLOL** [snyk/snyk#364]
To make sure my Scala packages (https://github.com/JohnReedLOL/pos and https://github.com/JohnReedLOL/scala-trace-debug) do not have known security vulnerabilities, I am considering between adding [https://github.com/albuch/sbt-dependency-check](https://github.com/albuch/sbt-dependency-check) or this "snyk" thing. The thing is, I see instructions for node and Docker, but I am not using node or Docker for my library. Should I use snyk or sbt-dependency-check, and if I use snyk, can I get a link to some super simple, straightforward setup instructions without much information that I would find extraneous?

p.s. I saw snyk here: https://i.ibb.co/M8RtJdv/Screen-Shot-2019-02-10-at-12-32-28-AM.png

**Comment by robcresswell** [comment]
The reason you're seeing node is because the CLI is a tool written in Node and can be installed via NPM, the Node Package Manager. Alternatively, there are other builds on the Releases page. https://github.com/snyk/snyk/releases/

Drop the OS-compatible release on your PATH and run it.

Scala docs are here: https://snyk.io/docs/snyk-for-scala/

Hope that was concise enough.

**Comment by darmalovan** [comment]
@JohnReedLOL I hope it answers your question, closing the issue for now.
