### ISSUE TITLE
Expected target framework is not present in proj file

### ISSUE THREAD

**Issue by alexanderkozlenko** [snyk/snyk#511]
- `node -v`: Unknown (GitHub integration)
- `npm -v`: Unknown (GitHub integration)
- `snyk -v`: Unknown (GitHub integration)
- Command run: Unknown (GitHub integration)

### Expected behavior

Snyk engine analyzed a C# project successfully.

### Actual behavior

Snyk engine failed to analyze a C# project with message "Expected target framework net472 is not present in proj file".

### Steps to reproduce

1. Create a public GitHub repository with a C# project targeting .NET Framework 4.7.2 .
2. Add Snyk integration for the repository.
3. Create a PR which changes target framework from 4.7.2 to 4.8

---

- Example PR: https://github.com/alexanderkozlenko/dotnet-launcher/pull/6
- The integrated Snyk check works fine on the same project for other changes.
- The mentioned message is provided only in a tooltip for a Snyk check, "Details" link navigates to an article which doesn't help to identify the problem.

**Comment by lili2311** [comment]
@alexanderkozlenko This is a limitation we are aware of, today every project is very coupled with the Target Framework. 

Each target framework in a project generates a completely different set of dependencies so we have to generate X projects if X target frameworks are present in the manifest file.

This means that once a framework is removed that particular project is no longer going to be updated. We have considered allowing users to just update the TF, but this is still something we are discussing as it doesn't quite feel right due to how different the dependencies will be in this scenario. It is essentially a brand new project in terms of dependencies.

The *work around* => re-import the project so we pick up the new framework & delete the old one. This means also updating the commit status checks on you side to not be required if that was set.

We are actively working towards allowing all of this to be more dynamic, so please stay tuned for future updates.

**Comment by alexanderkozlenko** [comment]
@lili2311, thank you for the explanation and workaround!

**Comment by alexanderkozlenko** [comment]
Hi @lili2311, I have the same error message for a PR where .NET framework version was not changed: https://github.com/alexanderkozlenko/dotnet-launcher/pull/19

**Comment by TMFRook** [comment]
Hey @lili2311, I seem to be getting this as well. Can I confirm whether this is still a known issue with Snyk?

**Comment by DominikPalo** [comment]
Do you have any updates? We have the same issue - we are migrating our projects from .NET 4.5.2 to .NET 4.6.2 and we are not able it run the Snyk tests on our "migration" branch, before merging that change to the `mater` branch... it is somehow possible to create two Snyk projects for different branches in the same repo?

Also, the "re-import the project" workaround is a bit unfortunate because we as developers don't have rights to manage Snyk projects, so we have to contact our company Snyk admins after every change of the .NET Framework version in any project...

**Comment by TMFRook** [comment]
@DominikPalo I was able to fix the issue by deleting the project and re-importing it, just like the recommendation here said.
