### ISSUE TITLE
Failed to patch 2 issues

### ISSUE THREAD

**Issue by kwstasna** [snyk/snyk#66]
- `node -v`: 6.9.4
- `npm -v`: 3.10.10
- `snyk -v`: 1.23.0-dev

- Command run: npm install

### Expected behaviour
install mean.io

### Actual behaviour
The patch against "node_modules\protractor\node_modules\minimatch" (npm:minimatch:20160620) failed.
The patch against "node_modules\swig\node_modules\uglify-js" (npm:uglify-js:20151024) failed.
Please email support@snyk.io if this problem persists.

### Steps to reproduce
on windows 10 x64.

$ patch -v
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@kwstasna sorry for the delayed reply!

Please try with the latest snyk (1.25.2 right now), and keep your `patch.exe` in `%PATH%`. Please reopen if this issue persists, and provide the output of `snyk protect -d` for debug info.

Version 1.23.0-dev was an attempt to rely on `git apply` instead of `patch`, but the two commands differ too much in behaviour, and we are not pursuing this direction right now. The proper use is to have `patch.exe` available in `%PATH%` when running `snyk protect`.
