### ISSUE TITLE
How does snyk CLI determine whether a project is private or public?

### ISSUE THREAD

**Issue by petermbenjamin** [snyk/snyk#69]
When I use `snyk wizard` command on an open-source/public repository in my terminal, it shows up on snyk.io as a **Private** project under the **Projects** tab.

If I click on **Test my Github repositories** button on the **Projects** page, I'm shown a list of repositories from my Github account that I can select to **Watch**, after which a project will appear on snyk.io as a **Public** project.

Is there a way I can add a project from the terminal as a **Public** project on snyk.io?
Or does `snyk wizard` always add projects as **Private**?

On a separate, yet related note, this phenomenon leads to duplication of projects on snyk.io.
At one point, I had several projects on snyk.io as **Public** (e.g. `petermbenjamin/some-project`) and **Private** (e.g. `some-project`) projects

**Comment by adrukh** [comment]
@petermbenjamin thanks for raising this.

`snyk wizard` will always classify projects as *Private*, and not keep any GitHub related metadata on the project. Unfortunately, there is no way to add a local project as a *Public* project due to this.

I would like to point out that the cli and GitHub integration are quite different in nature and serve different use-cases. With local projects, Snyk allows to test for vulns as part of your CI/CD cycle, and protect your project before it is being deployed. With GitHub repositories, Snyk allows you to maintain a vulnerability-free repo by testing your PRs and capturing snapshots for your project whenever your dependencies change. You can also use the 'Open a fix PR' feature to manage your Snyk policy. In both cases (local and GitHub), the last snapshot of the project is being tested when we publish new vulnerabilities, and the owner of the project is notified on such cases.

My recommendation would be to always Watch a repo, and use `snyk wizard` for cases where the project is not hosted on GitHub. You can still run `snyk test` and `snyk protect` on your checked-out code without creating a duplicate project with Snyk.

Hope this helps!

Anton

**Comment by petermbenjamin** [comment]
@adrukh - thanks for the quick response.

This certainly helps.

Would it be possible to consider a new `snyk watch` feature to **Watch** an open-source/public repo from the terminal?

**Comment by adrukh** [comment]
Thanks @petermbenjamin. Please open a separate issue for this feature request so we can track it.
