### ISSUE TITLE
Create a PR on the repo itself, not a fork

### ISSUE THREAD

**Issue by mattkrick** [snyk/snyk#72]
### Web app issue

I belong to a GH organization. On the snyk website, I click a repo within that organization. I click create PR with fixes. Instead of creating a PR on the repo itself, it creates a fork & then creates a PR on that fork. That means I have to merge the PR onto my fork, and then create a new PR from my fork to the repo I'm working on. Instead, I'd like snyk to add a PR to the org itself

### Expected behaviour
add a PR to the repo

### Actual behaviour
forks the repo into my account & creates a PR on that

### Steps to reproduce
1. click the create PR button in the web app for my repo (in this case: https://github.com/ParabolInc/action)
2. it creates a PR on my personal fork (https://github.com/mattkrick/action/pull/4)

**Comment by johannakoll** [comment]
Thanks Matt! I had a look at your account, and I can see that you have the "action" repo both in your personal GH context, and in the Parabollnc GH organisation that you are part off. You can watch both of these with Snyk, and you can create a pull request with fixes for both as well. 

It looks like you opened the PR for the repo in your personal GH context. If you go to [snyk.io/add](url) and scroll down, you'll see the "action" repo in the Parabollnc organisation, with an "Open fix PR" link next to it. Click that link, and then the PR with fixes will appear on https://github.com/ParabolInc/action instead of on mattkrick/action#4. 

Take-away for me is that the usability of snyk.io/add is not great, especially with the larger number of GH orgs and repos that I see you have. We actually have an iteration coming up that should make this easier to use, would you be up for getting a preview of that and giving us some feedback?

**Comment by mattkrick** [comment]
@johannakoll oh you're absolutely right, i didn't even notice the org headers, i was just looking at repo names. perhaps a sort by updatedAt? or adding the org to the repo name (eg "mattkrick/action" instead of action)? feel free to add me to any beta previews, would love to help get this popular!

**Comment by johannakoll** [comment]
@mattkrick good suggestions! the changes we are working on are even wider than that, and include a search as well. We'll have something to share this week; can give you access (via a feature flag) and for feedback we either do 15 min calls (with videosharing) if you're up for that - or just email.

**Comment by mattkrick** [comment]
sign me up! will close as user error for now.
