### ISSUE TITLE
Snyk doesn't honour gradle dependency resolution rules

### ISSUE THREAD

**Issue by seanjreilly** [snyk/snyk#729]
Given a gradle build that uses gradle's dependency resolution rules, snyk doesn't seem to analyse the dependencies actually used by the build. Instead it seems to use the dependencies as declared by the build before resolution.

Given a gradle build using spring boot 2.1.7, sneak rightly reports an issue with jackson-databind 2.9.9. If I use a dependency resolution rule to make gradle use jackson-databind 2.9.9.3 instead — which is my only option, because at the time I'm creating this issue, spring boot doesn't have a version that depends on the correct version of jackson-databind — snyk doesn't seem to register the change, even though the physical war file created has the safe version of the jackson-databind jar file in it.

- `snyk -v`: latest version of the jenkins snyk plugin (v2.10.0)
- `./gradlew -v`: Gradle 5.5.1
- Command run: gradlew clean build/ gradlew dependencies

### Expected behaviour
Snyk should honour the gradle dependency resolution rule and analyse using the jackson-databind dependency that gradle will actually use (2.9.9.3)

### Actual behaviour
Snyk reports the jackson-databind dependency as declared (2.9.9)

### Note
The Spring Boot gradle plugin does some things with dependencies, so I've created two minimal examples: a minimal spring boot example using the war plugin and spring boot plugins (my team's project uses spring boot, so this is what we would needs to honour the gradle dependency resolution rules), as well as an absolutely minimal example that doesn't use spring boot, and just uses a straightforward java dependency and the simplest possible expression of the resolution rule. Hope this helps.

### Steps to reproduce
1. Check out the git project: [https://github.com/vocalink/snyk-issue](https://github.com/vocalink/snyk-issue)
2. Build the master branch with `./gradlew clean build`
3. Run Snyk analysis (I did this via the Jenkins plugin — see the Jenkinsfile for usage) and note that Snyk reports several issues, including [SNYK-JAVA-COMFASTERXMLJACKSONCORE-455617](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-455617). Note that this issue is resolved by upgrading to jackson-databind 2.9.9.3.
4. Run `./gradlew dependencies | grep jackson-databind` and see that gradle is actually using jackson-databind 2.9.9.3
4. Open the generated warfile (rename snyk-issue.war to snyk-issue.zip and unzip) and examine the physical contents of the WEB-INF/lib directory. Confirm that jackson-databind-2.9.9.3.jar is the jarfile that is physically present in the archive.

The really stripped down example:
1. Check out the same [git project](https://github.com/vocalink/snyk-issue) branch jar-only
2. Run Snyk analysis for this branch (I did this via the Jenkins plugin — see the Jenkinsfile for usage) and note that Snyk again reports several issues that would be resolved by upgrading to jackson-databind 2.9.9.3.
3. Run `./gradlew dependencies | grep jackson-databind` and see that gradle is actually using jackson-databind 2.9.9.3

**Comment by kyegupov** [comment]
Hi Sean! Thank you for your report.

First, the behaviour depends on _how_ you declare the custom resolution rules. When it's done your way: 

    configurations*.resolutionStrategy versionStrategy

snyk will get the version 2.9.9, because we create a merged configuration on the fly to resolve the dependencies, and that one will not pick your custom rules. However, if you follow the examples from the Gradle documentation (https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html and https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) and write:

    configurations.all { resolutionStrategy versionStrategy }

you will get the proper version 2.9.9.3 (because `.all` applies the properties lazily and so will affect our configuration too). I'd recommend switching to that syntax.

However, I think we can handle your case too. I'll write a patch.

**Comment by kyegupov** [comment]
Unfortunately, it turns out, it's very hard to reliably transplant resolution strategy into our merged configuration. So, we can only recommend either of two workarounds:

* use `configurations.all` , as per Gradle documentation
* perform Snyk scans for a particular configuration: `snyk test --configuration-matching=^compile$` from the command line, or `snykSecurity(snykInstallation: 'snyk', snykTokenId: 'snyk-api-token', failOnIssues: false, additionalArguments: '--configuration-matching=^compile$')` in Jenkinsfile.

**Comment by seanjreilly** [comment]
It sounds like the merged configuration strategy might be somewhat risky — particularly when combined with other tools (such as spring boot) that also manipulate additional configurations.

That being said, the workaround you provided works as advertised, so I'm happy to close the issue.
