### ISSUE TITLE
The following option combination is not currently supported: ["file=*.sln","project-name"]

### ISSUE THREAD

**Issue by Noppey** [snyk/snyk#842]
My Azure Devops package Snyk Security Scan broke with this error:
The following option combination is not currently supported: ["file=*.sln","project-name"]

This seems related to https://github.com/snyk/snyk/pull/831

Command that is created through the package:
[command]C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\snyk.cmd monitor "--file=mysolution.sln" "--org=someguid" "--project-name=myprojectnameinsnyk""

**Comment by lili2311** [comment]
👋 This is intentional :) When `project-name` is used it overrides the project name and means that multiple projects could be treated as the same one overriding each other, this is a fix for the bug. Each manifest file is a project in the system so you can keep accurate project history. Please scan `sln` without the `project-name` or use `project-name` for each individual scanned manifest. 

I hope this clears things up
