### ISSUE TITLE
Snyk & Yarn compatibility with patching sub-dependencies

### ISSUE THREAD

**Issue by scoch** [snyk/snyk#86]
- `node -v`: v7.9.0
- `npm -v`: 4.2.0
- `snyk -v`: 1.30.1
- Command run:
snyk wizard

### Expected behaviour
Using yarn lock file
Snyk patches vulnerabilities of sub-dependencies

### Actual behaviour
An unknown error occurred. Please include the trace below when reporting to Snyk:

Error: Command failed: yarn remove  body-parser express express-nunjucks fstream-ignore gulp gulp-mocha gulp-nsp gulp-sass helmet knex mocha node-pre-gyp nunjucks serve-favicon supertest
error This module isn't specified in a manifest.

### Steps to reproduce
Use yarn for dependency management

using npm works as expected.

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
Hey just updating that this issue is acknowledged, and we will work on a fix in the next few days. Stay tuned!

**Comment by deebugger** [comment]
This issue has been resolved in version 1.31.1 of the Snyk CLI tool.
To upgrade, simply run 'npm install -f snyk'.

**Comment by scoch** [comment]
Fantastic, and thanks for the speedy response as usual folks. Greatly appreciated 👍

**Comment by adrukh** [comment]
@scoch we ran into a case where our current fix was insufficient. A presence of an extraneous dependency that leads to a vulnerable dependency, and needs to be reinstalled, will cause us to fail while `yarn remove`-ing an extraneous dependency. Running `npm prune` should take care of that for you. Hope this helps!

**Comment by msavy** [comment]
@adrukh still get this issue when testing with the latest version, including your latest hints on apicurio.

clone https://github.com/Apicurio/apicurio-studio
cd to apicurio-studio/front-end/app
snyk wizard

Here's a gist (other combinations seem to fail similarly): https://gist.github.com/msavy/06a3727646e0a5bb1120f3a08e26222f

**Comment by adrukh** [comment]
@msavy thanks a lot, finally a reproduction I can work with!

`yarn.lock` calls for `node-pre-gyp`, which is added as an extraneous dependency, and leads to a lower-hanging vuln. Our remediation calls for re-install of `node-pre-gyp`, but it does not appear in `package.json`, hence failing `yarn remove ... node-pre-gyp ...` over strictness (`npm uninstall ... node-pre-gyp ...` skips the missing dep without failing).

Using `npm install` instead of `yarn` does not introduce the extraneous dep, and passes `snyk wizard`. Removing the committed `yarn.lock`, I'd expect `yarn` to create a clean lockfile, but it does re-introduce `node-pre-gyp`, which is then identified as extraneous! Definitely something to look deeper into, I'll update here as we go.

We will work on a change to the way we handle extraneous dependencies to both alert about vulnerabilities they introduce, AND not fail over their presence!

**Comment by lirantal** [comment]
Holy molly! interesting. so wait, are you saying @adrukh that yarn itself superficially adds the `node-pre-gyp` package to yarn.lock as well as to node_modules?

**Comment by adrukh** [comment]
We'll be releasing a fix tomorrow to address this. I'll post more details here about the change in behaviour.

In the meantime, I opened an issue for yarn - https://github.com/yarnpkg/yarn/issues/3581 using the reproduction @msavy provided - thanks again, it helped a lot!

**Comment by msavy** [comment]
Thanks @adrukh. We look forwards to trying Snyk on apicurio!

**Comment by msavy** [comment]
@adrukh -- when running snyk wizard I see this (last line): https://gist.github.com/msavy/eec09eff177674f35e4dbd248afac1bf#file-gistfile1-txt-L81

Not sure if it's important?

**Comment by msavy** [comment]
Oh, seems you fixed it with an update 1.33.2 :-)

**Comment by adrukh** [comment]
Yes, a sloppy move on my end there... 😳

**Comment by msavy** [comment]
Seems to work OK, so thumbs up from me. Caveat being it's the first time I've used Snyk so probably a weaker datapoint.
