### ISSUE TITLE
snyk protect fail on Travis

### ISSUE THREAD

**Issue by jaumard** [snyk/snyk#90]
- `node -v`: 8 or 7 or 6
- `npm -v`: 5.0.3
- `snyk -v`: 1.34.4
- Command run:
snyk protect
### Expected behaviour
Correct patch

### Actual behaviour
`The patch against "node_modules/qs" (npm:qs:20170213) failed.`

### Steps to reproduce
https://travis-ci.org/mylisabox/lisa-box/jobs/244223676

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by adrukh** [comment]
@jaumard 👋 

Thanks for reporting this!

Checking your travis settings, I see that only the node 8 build fails. I suspect there is something fishy with the cached dependencies for this build.

If this is keeping you from releasing, a workaround I can suggest is to clear travis' cache and restart the build.

I would, however, love to get a better view of the problem we are seeing. Two options for this:
1. On https://github.com/mylisabox/lisa-box/blob/master/package.json#L8, please change the command `snyk protect` to `snyk protect -d`. It will show much more info and give an insight into the failure once it runs on travis.
2. Use travis' `debug build` feature by ssh-ing into the build and running `snyk protect -d` manually to collect the output.

I'd love to see what the issue is!

Cheers,
Anton

**Comment by jaumard** [comment]
Thanks for the quick answer @adrukh :)

in this build it was node 6 and 7 who fail because of this https://travis-ci.org/mylisabox/lisa-box/builds/244217925

I enable the -d option on this build not sure it will help https://travis-ci.org/mylisabox/lisa-box/jobs/244232990

```
snyk patched { patch: 
   { 'npm:ms:20170412': [ [Object], [Object], [Object], [Object], [Object] ],
     'npm:qs:20170213': [ [Object] ] } } +17ms
The patch against "node_modules/qs" (npm:qs:20170213) failed.
  snyk add success false +6ms
  snyk add error-message Please email support@snyk.io if this problem persists. +1ms
  snyk add error Error: Please email support@snyk.io if this problem persists.
    at /home/travis/build/mylisabox/lisa-box/node_modules/snyk/lib/protect/patch.js:203:13
    at tryCatch (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9) +0ms
  snyk add error-code undefined +0ms
  msnyk add command protect +0ms
Error: Please email support@snyk.io if this problem persists.
    at /home/travis/build/mylisabox/lisa-box/node_modules/snyk/lib/protect/patch.js:203:13
    at tryCatch (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at flush (/home/travis/build/mylisabox/lisa-box/node_modules/es6-promise/dist/es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by jaumard** [comment]
On this node 8 build it's green but fail the two first try before with same error https://travis-ci.org/mylisabox/lisa-box/jobs/244234445

**Comment by adrukh** [comment]
Ok, I was able to reproduce this locally by cloning the repo, running `snyk protect` once (successfully) and then for the second time (failing!)

I will continue looking into this, but cannot promise a specific timeframe. Go ahead and clear your dependencies cache as a workaround, this should help push the travis build to green.

I'll update here once I have something!

**Comment by adrukh** [comment]
Ok some more info. We are thrown off by the fact `qs@6.3.0` is only detected on the
`sqlite3 > node-pre-gyp > request > qs` path, but we are detecting a `qs@6.3.0` module at the somewhat long path of
`sonus@0.1.8 > @google-cloud/speech@0.9.3 > @google-cloud/common@0.13.3 > google-auto-auth@0.6.1 > gcp-metadata@0.1.0 > retry-request@1.3.2 > request@2.76.0 > qs@6.3.0`

This path is misdetected (doesn't seem to exist), which probably leads us to try and patch another `qs` dep located in `node_modules`. All other qs deps are either `6.3.2` or `6.4.0`, which are not affected by this vuln. Trying to patch them fails because their code already includes this patch.

This is a step forward in my understanding of the issue, so thanks for the very clear example. I may still be off here, but have more to work on.

I also think that the fact `node-pre-gyp` is bundled with `sqlite3` is helping to throw us off...

**Comment by jaumard** [comment]
@adrukh thanks for looking at this issue :) I understand the problem now ^^ I'll try to if some of those deps can be upgraded, like this no more problem too :)
